[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
solc_version = "0.8.28"
optimizer = true
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

[fuzz]
runs = 1024
