[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
solc_version = "0.8.28"
optimizer = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
base = "${BASE_RPC_URL}"

[fuzz]
runs = 1024


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
